export interface CelestialBody {
  slug: string
  name: string
  type: "star" | "planet" | "dwarf-planet"
  tagline: string
  description: string
  orderFromSun: number
  // Physical
  radiusKm: number
  massKg: string // scientific notation string
  surfaceGravity: number // m/s2
  escapeVelocity: number // km/s
  // Orbital
  dayLengthHours: number
  yearLengthDays: number
  rotationSpeedKmh: number // at equator
  distanceFromSunKm: string
  orbitalSpeedKmS: number
  // Environment
  surfaceTempC: { min: number; max: number; avg: number }
  atmosphere: { gas: string; percent: number }[]
  composition: string
  hasRings: boolean
  hasSurface: boolean
  surfaceType: string
  moons: number
  // Human factors
  survivalEstimate: string
  survivalSeconds: number // approximate seconds you'd survive
  ageFactor: number // 1 Earth year = ageFactor planet years
  weightMultiplier: number // relative to Earth (Earth = 1)
  // Visual
  color: string // primary hex color
  accentColor: string
  ringColor?: string
  funFacts: string[]
}

export const solarSystemData: CelestialBody[] = [
  {
    slug: "sun",
    name: "The Sun",
    type: "star",
    tagline: "Our local star",
    description: "The Sun is a G-type main-sequence star (G2V) at the center of our solar system. It contains 99.86% of the total mass of the solar system. Its core temperature reaches 15 million degrees Celsius, where hydrogen fuses into helium through nuclear fusion, releasing the energy that powers all life on Earth. The Sun is approximately 4.6 billion years old and is expected to remain on the main sequence for another 5 billion years.",
    orderFromSun: 0,
    radiusKm: 696340,
    massKg: "1.989 x 10^30",
    surfaceGravity: 274,
    escapeVelocity: 617.7,
    dayLengthHours: 609.12, // ~25.38 Earth days at equator
    yearLengthDays: 0, // N/A
    rotationSpeedKmh: 7189,
    distanceFromSunKm: "0",
    orbitalSpeedKmS: 0,
    surfaceTempC: { min: 5500, max: 15000000, avg: 5500 },
    atmosphere: [{ gas: "Hydrogen", percent: 73.46 }, { gas: "Helium", percent: 24.85 }, { gas: "Oxygen", percent: 0.77 }, { gas: "Carbon", percent: 0.29 }],
    composition: "Hydrogen and helium plasma",
    hasRings: false,
    moons: 0,
    survivalEstimate: "Instant vaporization",
    survivalSeconds: 0,
    ageFactor: 0,
    weightMultiplier: 27.9,
    color: "#FDB813",
    accentColor: "#FF6B00",
    funFacts: [
      "Light from the Sun takes 8 minutes 20 seconds to reach Earth",
      "The Sun loses 4 million tonnes of mass every second through fusion",
      "Over one million Earths could fit inside the Sun",
      "The Sun's core pressure is 265 billion atmospheres",
    ],
  },
  {
    slug: "mercury",
    name: "Mercury",
    type: "planet",
    tagline: "The swift messenger",
    description: "Mercury is the smallest planet in our solar system and the closest to the Sun. Despite being closest to the Sun, it is not the hottest planet (Venus holds that title). Mercury has virtually no atmosphere to retain heat, causing extreme temperature swings between its day and night sides. Its surface is heavily cratered, resembling Earth's Moon, and it has a surprisingly large iron core that takes up about 75% of its radius.",
    orderFromSun: 1,
    radiusKm: 2439.7,
    massKg: "3.301 x 10^23",
    surfaceGravity: 3.7,
    escapeVelocity: 4.25,
    dayLengthHours: 4222.6, // 176 Earth days
    yearLengthDays: 87.97,
    rotationSpeedKmh: 10.89,
    distanceFromSunKm: "57.9 million",
    orbitalSpeedKmS: 47.87,
    surfaceTempC: { min: -180, max: 430, avg: 167 },
    atmosphere: [{ gas: "Sodium", percent: 29 }, { gas: "Hydrogen", percent: 22 }, { gas: "Helium", percent: 6 }, { gas: "Oxygen", percent: 43 }],
    composition: "Iron core (75%), silicate mantle and crust",
    hasRings: false,
    moons: 0,
    survivalEstimate: "~90 seconds without a spacesuit",
    survivalSeconds: 90,
    ageFactor: 4.15,
    weightMultiplier: 0.38,
    color: "#A0522D",
    accentColor: "#CD853F",
    funFacts: [
      "A day on Mercury (sunrise to sunrise) lasts 176 Earth days",
      "Mercury is shrinking as its iron core cools",
      "It has ice in permanently shadowed craters at its poles",
      "Mercury has no moons or rings",
    ],
  },
  {
    slug: "venus",
    name: "Venus",
    type: "planet",
    tagline: "Earth's evil twin",
    description: "Venus is the second planet from the Sun and the hottest in our solar system. Its thick atmosphere of carbon dioxide creates a runaway greenhouse effect, trapping heat and raising surface temperatures to 465 degrees C, hot enough to melt lead. Atmospheric pressure on Venus is 90 times that of Earth. Venus rotates backwards (retrograde rotation) and so slowly that a day on Venus is longer than its year. Despite its hellish conditions, scientists speculate that microbial life could potentially exist in its upper cloud layers.",
    orderFromSun: 2,
    radiusKm: 6051.8,
    massKg: "4.867 x 10^24",
    surfaceGravity: 8.87,
    escapeVelocity: 10.36,
    dayLengthHours: 5832, // 243 Earth days (retrograde)
    yearLengthDays: 224.7,
    rotationSpeedKmh: 6.52,
    distanceFromSunKm: "108.2 million",
    orbitalSpeedKmS: 35.02,
    surfaceTempC: { min: 462, max: 470, avg: 464 },
    atmosphere: [{ gas: "Carbon Dioxide", percent: 96.5 }, { gas: "Nitrogen", percent: 3.5 }],
    composition: "Iron core, silicate mantle, basaltic crust",
    hasRings: false,
    moons: 0,
    survivalEstimate: "Less than 1 second on the surface",
    survivalSeconds: 1,
    ageFactor: 1.63,
    weightMultiplier: 0.91,
    color: "#E8CDA0",
    accentColor: "#DEB887",
    funFacts: [
      "Venus spins backwards compared to most planets",
      "A day on Venus is longer than its year",
      "Surface pressure is equivalent to being 900m underwater on Earth",
      "Venus is the brightest natural object in the night sky after the Moon",
    ],
  },
  {
    slug: "earth",
    name: "Earth",
    type: "planet",
    tagline: "Our home world",
    description: "Earth is the third planet from the Sun and the only known world to harbor life. Its unique combination of liquid water, a protective magnetic field, a breathable atmosphere, and moderate temperatures make it a haven for an extraordinary diversity of life forms. Earth's surface is 71% water, and its atmosphere is primarily nitrogen (78%) and oxygen (21%). The planet's axial tilt of 23.5 degrees gives rise to seasons, while the Moon stabilizes this tilt over long periods. Earth is approximately 4.54 billion years old.",
    orderFromSun: 3,
    radiusKm: 6371,
    massKg: "5.972 x 10^24",
    surfaceGravity: 9.81,
    escapeVelocity: 11.19,
    dayLengthHours: 24,
    yearLengthDays: 365.25,
    rotationSpeedKmh: 1674.4,
    distanceFromSunKm: "149.6 million",
    orbitalSpeedKmS: 29.78,
    surfaceTempC: { min: -89, max: 57, avg: 15 },
    atmosphere: [{ gas: "Nitrogen", percent: 78.09 }, { gas: "Oxygen", percent: 20.95 }, { gas: "Argon", percent: 0.93 }, { gas: "CO2", percent: 0.04 }],
    composition: "Iron-nickel core, silicate mantle, varied crust",
    hasRings: false,
    moons: 1,
    survivalEstimate: "Average lifespan: ~73 years",
    survivalSeconds: -1,
    ageFactor: 1,
    weightMultiplier: 1,
    color: "#4169E1",
    accentColor: "#228B22",
    funFacts: [
      "Earth is the densest planet in the solar system",
      "The planet's magnetic field is generated by its liquid iron outer core",
      "Earth is the only planet not named after a Greek or Roman god",
      "70% of Earth's surface is covered in water, but 97% of that is saltwater",
    ],
  },
  {
    slug: "mars",
    name: "Mars",
    type: "planet",
    tagline: "The red planet",
    description: "Mars is the fourth planet from the Sun, known for its distinctive red color caused by iron oxide (rust) on its surface. Mars has the largest volcano in the solar system (Olympus Mons, 21.9 km high) and a canyon system (Valles Marineris) that dwarfs Earth's Grand Canyon. Evidence suggests Mars once had liquid water on its surface, and NASA's rovers have found signs of ancient river beds and lake deposits. Mars is a primary target for future human colonization, with NASA's Artemis program building the infrastructure needed to eventually send humans there.",
    orderFromSun: 4,
    radiusKm: 3389.5,
    massKg: "6.417 x 10^23",
    surfaceGravity: 3.72,
    escapeVelocity: 5.03,
    dayLengthHours: 24.62,
    yearLengthDays: 687,
    rotationSpeedKmh: 868.22,
    distanceFromSunKm: "227.9 million",
    orbitalSpeedKmS: 24.07,
    surfaceTempC: { min: -140, max: 20, avg: -63 },
    atmosphere: [{ gas: "Carbon Dioxide", percent: 95.32 }, { gas: "Nitrogen", percent: 2.7 }, { gas: "Argon", percent: 1.6 }, { gas: "Oxygen", percent: 0.13 }],
    composition: "Iron sulfide core, silicate mantle, basaltic crust",
    hasRings: false,
    moons: 2,
    survivalEstimate: "~2 minutes without a pressure suit",
    survivalSeconds: 120,
    ageFactor: 0.53,
    weightMultiplier: 0.38,
    color: "#CD4F39",
    accentColor: "#FF6347",
    funFacts: [
      "Olympus Mons is nearly 3x the height of Mount Everest",
      "Mars has seasons like Earth due to its similar axial tilt (25.2 degrees)",
      "A day on Mars (a 'sol') is only 37 minutes longer than an Earth day",
      "Mars has two tiny moons, Phobos and Deimos, likely captured asteroids",
    ],
  },
  {
    slug: "jupiter",
    name: "Jupiter",
    type: "planet",
    tagline: "King of the planets",
    description: "Jupiter is the fifth planet from the Sun and the largest in our solar system, with a mass more than twice that of all other planets combined. It is a gas giant with no solid surface, composed primarily of hydrogen and helium. Jupiter's Great Red Spot is a storm larger than Earth that has raged for over 350 years. The planet has a powerful magnetic field and at least 95 known moons, including the four large Galilean moons: Io (the most volcanically active body in the solar system), Europa (which may harbor a subsurface ocean), Ganymede (the largest moon in the solar system), and Callisto.",
    orderFromSun: 5,
    radiusKm: 69911,
    massKg: "1.898 x 10^27",
    surfaceGravity: 24.79,
    escapeVelocity: 59.5,
    dayLengthHours: 9.93,
    yearLengthDays: 4333,
    rotationSpeedKmh: 45583,
    distanceFromSunKm: "778.5 million",
    orbitalSpeedKmS: 13.07,
    surfaceTempC: { min: -160, max: -100, avg: -110 },
    atmosphere: [{ gas: "Hydrogen", percent: 89.8 }, { gas: "Helium", percent: 10.2 }],
    composition: "Hydrogen/helium gas, metallic hydrogen mantle, rocky core",
    hasRings: true,
    moons: 95,
    survivalEstimate: "Instant crush from atmospheric pressure",
    survivalSeconds: 0,
    ageFactor: 0.084,
    weightMultiplier: 2.53,
    color: "#C88B3A",
    accentColor: "#DEB887",
    funFacts: [
      "Jupiter's Great Red Spot could fit 2-3 Earths inside it",
      "Jupiter has the shortest day of any planet (9h 55m)",
      "Its magnetic field is 20,000x stronger than Earth's",
      "Europa's subsurface ocean may contain more water than all of Earth's oceans",
    ],
  },
  {
    slug: "saturn",
    name: "Saturn",
    type: "planet",
    tagline: "The ringed wonder",
    description: "Saturn is the sixth planet from the Sun, famous for its spectacular ring system made of ice and rock particles ranging in size from tiny grains to house-sized boulders. Saturn is the least dense planet, so light it would float in water if you could find a bathtub large enough. Like Jupiter, it is a gas giant composed mostly of hydrogen and helium. Saturn's moon Titan has a thick nitrogen atmosphere and liquid methane lakes, making it one of the most Earth-like worlds in the solar system despite its frigid temperatures. Enceladus, another moon, shoots geysers of water ice into space from a subsurface ocean.",
    orderFromSun: 6,
    radiusKm: 58232,
    massKg: "5.683 x 10^26",
    surfaceGravity: 10.44,
    escapeVelocity: 35.5,
    dayLengthHours: 10.7,
    yearLengthDays: 10759,
    rotationSpeedKmh: 36840,
    distanceFromSunKm: "1.43 billion",
    orbitalSpeedKmS: 9.68,
    surfaceTempC: { min: -180, max: -120, avg: -140 },
    atmosphere: [{ gas: "Hydrogen", percent: 96.3 }, { gas: "Helium", percent: 3.25 }],
    composition: "Hydrogen/helium gas, metallic hydrogen, rocky core",
    hasRings: true,
    moons: 146,
    survivalEstimate: "Instant crush from pressure and wind",
    survivalSeconds: 0,
    ageFactor: 0.034,
    weightMultiplier: 1.07,
    color: "#E8D191",
    accentColor: "#DAA520",
    ringColor: "#C9B87C",
    funFacts: [
      "Saturn's rings span 282,000 km but are only about 10 meters thick",
      "Saturn is less dense than water (0.687 g/cm3)",
      "Wind speeds on Saturn can reach 1,800 km/h",
      "Titan is the only moon in the solar system with a substantial atmosphere",
    ],
  },
  {
    slug: "uranus",
    name: "Uranus",
    type: "planet",
    tagline: "The sideways planet",
    description: "Uranus is the seventh planet from the Sun and an ice giant. Its most distinctive feature is its extreme axial tilt of 97.77 degrees, meaning it essentially orbits the Sun on its side. This is thought to be the result of a collision with an Earth-sized body long ago. Uranus has a blue-green color due to methane in its atmosphere, which absorbs red light. It has 27 known moons (all named after characters from Shakespeare and Alexander Pope), a faint ring system, and the coldest planetary atmosphere in the solar system at -224 degrees C.",
    orderFromSun: 7,
    radiusKm: 25362,
    massKg: "8.681 x 10^25",
    surfaceGravity: 8.87,
    escapeVelocity: 21.3,
    dayLengthHours: 17.24,
    yearLengthDays: 30687,
    rotationSpeedKmh: 9320,
    distanceFromSunKm: "2.87 billion",
    orbitalSpeedKmS: 6.81,
    surfaceTempC: { min: -224, max: -200, avg: -214 },
    atmosphere: [{ gas: "Hydrogen", percent: 82.5 }, { gas: "Helium", percent: 15.2 }, { gas: "Methane", percent: 2.3 }],
    composition: "Water, methane, ammonia ices over rocky core",
    hasRings: true,
    moons: 27,
    survivalEstimate: "Instant death from cold and pressure",
    survivalSeconds: 0,
    ageFactor: 0.012,
    weightMultiplier: 0.91,
    color: "#73C2FB",
    accentColor: "#87CEEB",
    funFacts: [
      "Uranus rotates on its side with a 97.77 degree axial tilt",
      "It was the first planet discovered with a telescope (1781)",
      "All 27 moons are named after Shakespeare and Pope characters",
      "Uranus has the coldest atmosphere of any planet (-224 degrees C)",
    ],
  },
  {
    slug: "neptune",
    name: "Neptune",
    type: "planet",
    tagline: "The windiest world",
    description: "Neptune is the eighth and farthest planet from the Sun. It is an ice giant similar in composition to Uranus but with a more vivid blue color. Neptune has the strongest sustained winds of any planet, reaching speeds of 2,100 km/h. Its largest moon, Triton, orbits in the opposite direction to Neptune's rotation (retrograde orbit), suggesting it was captured from the Kuiper Belt. Triton has geysers that shoot nitrogen gas 8 km into the sky. Neptune was the first planet located through mathematical prediction rather than direct observation.",
    orderFromSun: 8,
    radiusKm: 24622,
    massKg: "1.024 x 10^26",
    surfaceGravity: 11.15,
    escapeVelocity: 23.5,
    dayLengthHours: 16.11,
    yearLengthDays: 60190,
    rotationSpeedKmh: 9719,
    distanceFromSunKm: "4.5 billion",
    orbitalSpeedKmS: 5.43,
    surfaceTempC: { min: -218, max: -200, avg: -214 },
    atmosphere: [{ gas: "Hydrogen", percent: 80 }, { gas: "Helium", percent: 19 }, { gas: "Methane", percent: 1.5 }],
    composition: "Water, methane, ammonia ices over rocky core",
    hasRings: true,
    moons: 16,
    survivalEstimate: "Instant death from cold and wind",
    survivalSeconds: 0,
    ageFactor: 0.006,
    weightMultiplier: 1.14,
    color: "#4169E1",
    accentColor: "#1E90FF",
    funFacts: [
      "Neptune's winds are the fastest in the solar system at 2,100 km/h",
      "It was discovered mathematically before being seen through a telescope",
      "Neptune takes 164.8 Earth years to orbit the Sun",
      "Triton is slowly spiraling inward and will eventually be torn apart by Neptune's gravity",
    ],
  },
  {
    slug: "pluto",
    name: "Pluto",
    type: "dwarf-planet",
    tagline: "The beloved dwarf planet",
    description: "Pluto was reclassified as a dwarf planet in 2006 but remains one of the most fascinating objects in our solar system. Located in the Kuiper Belt, Pluto has a heart-shaped nitrogen ice glacier (Tombaugh Regio) that was revealed in stunning detail by NASA's New Horizons flyby in 2015. Pluto has five known moons, with Charon being so large relative to Pluto that the two are sometimes considered a binary system. The pair are tidally locked, always showing the same face to each other. Pluto's thin atmosphere expands and collapses as it moves closer to and farther from the Sun in its highly elliptical orbit.",
    orderFromSun: 9,
    radiusKm: 1188.3,
    massKg: "1.303 x 10^22",
    surfaceGravity: 0.62,
    escapeVelocity: 1.21,
    dayLengthHours: 153.3, // 6.39 Earth days
    yearLengthDays: 90560, // 248 Earth years
    rotationSpeedKmh: 47.18,
    distanceFromSunKm: "5.9 billion",
    orbitalSpeedKmS: 4.67,
    surfaceTempC: { min: -240, max: -218, avg: -229 },
    atmosphere: [{ gas: "Nitrogen", percent: 90 }, { gas: "Methane", percent: 8 }, { gas: "Carbon Monoxide", percent: 2 }],
    composition: "Ice and rock, nitrogen ice surface",
    hasRings: false,
    moons: 5,
    survivalEstimate: "Instant death from cold and vacuum",
    survivalSeconds: 0,
    ageFactor: 0.004,
    weightMultiplier: 0.063,
    color: "#C2B280",
    accentColor: "#DEB887",
    funFacts: [
      "Pluto's heart-shaped feature (Tombaugh Regio) is larger than Texas",
      "Pluto and Charon are tidally locked to each other",
      "Pluto's orbit is so elliptical it sometimes comes closer to the Sun than Neptune",
      "New Horizons took 9.5 years to reach Pluto, travelling at 58,000 km/h",
    ],
  },
]
